version: "3"

services:
  restapi:
    image: vlee489/ac51041-restapi
    container_name: devops_restapi
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file:
      - .config/api.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rest.rule=Host(`devops.vlee.me.uk`)"
      - "traefik.http.routers.rest.entrypoints=websecure"
      - "traefik.http.routers.rest.tls.certresolver=mydnschallenge"

  webUI:
    image: vlee489/ac51041-ui
    container_name: devops_ui
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`devui.vlee.me.uk`)"
      - "traefik.http.routers.ui.entrypoints=websecure"
      - "traefik.http.routers.ui.tls.certresolver=mydnschallenge"

  login:
    image: vlee489/ac51041-login
    container_name: devops_login
    restart: unless-stopped
    depends_on:
      - redis
      - db
      - rabbitmq
    links:
      - rabbitmq
    env_file:
      - .config/login.env

  catalogue:
    image: vlee489/ac51041-catalogue
    container_name: devops_catalogue
    restart: unless-stopped
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    env_file:
      - .config/catalogue.env

  signer:
    image: vlee489/ac51041-signer
    container_name: devops_signer
    restart: unless-stopped
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    env_file:
      - .config/signer.env

  personalisation:
    image: vlee489/ac51041-personalisation
    container_name: devops_personalisation
    restart: unless-stopped
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    env_file:
      - .config/personalisation.env

  redis:
    image: "redis:alpine"
    container_name: devops_redis
    restart: unless-stopped

  db:
    restart: unless-stopped
    image: docker.io/postgres:12.2-alpine
    container_name: devops_db
    env_file:
      - .config/db.env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    restart: unless-stopped
    image: "rabbitmq:3-management"
    container_name: devops_rabbitmq
    ports:
      - "15672:15672"

  traefik:
    image: "traefik:v2.9"
    container_name: devops_traefik
    restart: unless-stopped
    env_file: .config/proxy.env
    depends_on:
      - restapi
    command:
      - "--api.dashboard=false"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge=true"
#      - "--certificatesresolvers.mydnschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.mydnschallenge.acme.email=vlee@vlee.me.uk"
      - "--certificatesresolvers.mydnschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"